<?php
/**
 * AnalyzeDocumentResponseEntityDocumentImagesTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Dojah
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * DOJAH APIs
 *
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Dojah\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AnalyzeDocumentResponseEntityDocumentImagesTest Class Doc Comment
 *
 * @category    Class
 * @description AnalyzeDocumentResponseEntityDocumentImages
 * @package     Dojah
 */
class AnalyzeDocumentResponseEntityDocumentImagesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AnalyzeDocumentResponseEntityDocumentImages"
     */
    public function testAnalyzeDocumentResponseEntityDocumentImages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "portrait"
     */
    public function testPropertyPortrait()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fingerprint"
     */
    public function testPropertyFingerprint()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "document_front_side"
     */
    public function testPropertyDocumentFrontSide()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
