<?php
/**
 * FraudGetIpReputationResponseEntityReportTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Dojah
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * DOJAH Publilc APIs
 *
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Dojah\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FraudGetIpReputationResponseEntityReportTest Class Doc Comment
 *
 * @category    Class
 * @description FraudGetIpReputationResponseEntityReport
 * @package     Dojah
 */
class FraudGetIpReputationResponseEntityReportTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FraudGetIpReputationResponseEntityReport"
     */
    public function testFraudGetIpReputationResponseEntityReport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "blacklists"
     */
    public function testPropertyBlacklists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "information"
     */
    public function testPropertyInformation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "anonymity"
     */
    public function testPropertyAnonymity()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "risk_score"
     */
    public function testPropertyRiskScore()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
