<?php
/**
 * GetAccountAnalysisResponseEntityAccountBreakdownTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Dojah
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * DOJAH APIs
 *
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Dojah\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetAccountAnalysisResponseEntityAccountBreakdownTest Class Doc Comment
 *
 * @category    Class
 * @description GetAccountAnalysisResponseEntityAccountBreakdown
 * @package     Dojah
 */
class GetAccountAnalysisResponseEntityAccountBreakdownTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetAccountAnalysisResponseEntityAccountBreakdown"
     */
    public function testGetAccountAnalysisResponseEntityAccountBreakdown()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_credit_entry"
     */
    public function testPropertyTotalCreditEntry()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_debit_made"
     */
    public function testPropertyTotalDebitMade()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "average_monthly_balance"
     */
    public function testPropertyAverageMonthlyBalance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "average_monthly_credits"
     */
    public function testPropertyAverageMonthlyCredits()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "average_monthly_debits"
     */
    public function testPropertyAverageMonthlyDebits()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "average_weekly_balance"
     */
    public function testPropertyAverageWeeklyBalance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "average_weekly_credits"
     */
    public function testPropertyAverageWeeklyCredits()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "average_weekly_debits"
     */
    public function testPropertyAverageWeeklyDebits()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "closing_balance"
     */
    public function testPropertyClosingBalance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "first_date_in_statement"
     */
    public function testPropertyFirstDateInStatement()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_date_in_statement"
     */
    public function testPropertyLastDateInStatement()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "number_of_transacting_months"
     */
    public function testPropertyNumberOfTransactingMonths()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "period_in_statement"
     */
    public function testPropertyPeriodInStatement()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "year_in_statement"
     */
    public function testPropertyYearInStatement()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
