<?php

/**
 * GHKYCApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Dojah
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * DOJAH APIs
 *
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Dojah\Test\Api;

use \Dojah\Configuration;
use \Dojah\ApiException;
use \Dojah\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class GHKYCApiTest extends TestCase
{

    protected \Dojah\Api\GHKYCApi $api;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $apiKey = getenv("DOJAH_API_KEY");
        $appId = getenv("DOJAH_APP_ID");
        print_r($apiKey);
        print_r($appId);
        $dojah = new \Dojah\Client(
            Authorization: $apiKey,
            AppId: $appId,
            host: "https://sandbox.dojah.io"
        );
        $this->api = $dojah->ghKyc;
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getDriversLicense
     *
     * Driver's License.
     *
     */
    public function testGetDriversLicense()
    {
        $response = $this->api->getDriversLicense(id: "V0000000", full_name: "John Doe", date_of_birth: "1988-09-01");
        $this->assertNotNull(
            $response,
            "response is null"
        );
    }

    /**
     * Test case for getPassport
     *
     * Passport.
     *
     */
    public function testGetPassport()
    {
        $response = $this->api->getPassport(id: "V0000000", first_name: "John", last_name: "Doe", date_of_birth: "1988-09-01");
        $this->assertNotNull(
            $response,
            "response is null"
        );
    }

    /**
     * Test case for getSsnit
     *
     * SSNIT.
     *
     */
    public function testGetSsnit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}